TFP/TFP/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from designers.views import (designer_orders,  change_order_status, designer_business)
from customers.views import (remove_from_wishlist, create_order, orders_view, history, submit_review)
from customers.views import (add_to_wishlist, wishlist, cart, men_bottomwear, women_fusion, women_ethnic)
from account.views import (index_login_view, registration, user_login, logout_view, error)
from designers.views import (update_stock,delete_product_view,delete_product,edit_designer_profile,designer_dashboard,add_product_view,add_product,base,update,designer_registration,edit_info,)
from customers.views import (designer_profile,all_products,men_topwear,product_detail,userpage2,customer_dashboard,userpage1,user_profile,edit_customer_address)
from django.conf.urls.static import static

urlpatterns = [

    # admin
    path('admin/', admin.site.urls),
    # index
    path('', index_login_view, name="index"),
    
    # error
    path('error', error , name="error"),

    # ----------------------------------------------------------------------------------------------------------
    # registration and login

    # unwanted
    path('register',designer_registration, name='register'),
    # registration
    path('registration',registration, name='registration'),
    # login
    path('user_login',user_login, name='user_login'),
    # logout
    path('logout_view', logout_view, name='logout_view'),

    # ------------------------------------------------------------------------------------------------------------
    # designer url's

    # desginer dashboard
    path('designer',designer_dashboard, name='designer_dashboard'),
    # designer base
    path('base',base),
    # edit profile - designer
    path('edit_info',edit_info, name='edit_info'),
    # edit designer profile - function
    path('edit_designer_profile',edit_designer_profile, name="edit_designer_profile"),
    
  

    
    # --------------------------------------------------------------------------------------------------------------
    # product url's

    # add new product
    path('addPrd',add_product_view, name='addPrd'),
    # add new product function
    path('add_product',add_product, name='add_product'),
    # add new product
    path('delete_product_view',delete_product_view, name='delete_product_view'),
    # delete product function
    path('product/<int:pk>/delete/', delete_product, name='delete_product'),
    # update product stock 
    path('update',update, name='update'),
    # udate product stock funstion
    #path('<int:pk>/update_stock/', update_stock, name='update_stock'),
    path('update/<int:pk>/', update_stock, name='update'),
    #take all products from db to user page 
    path('all_products/', all_products, name='all_products'),
    # product detail
    path('product/<int:pk>/',product_detail, name='product_detail'),


# ----------------------------------------------------------
    # view men's topwear
    path('men_topwear', men_topwear , name='men_topwear'),
    # view men's bottomwear
    path('men_bottomwear', men_bottomwear , name='men_bottomwear'),
    # view women_fusion
    path('women_fusion', women_fusion , name='women_fusion'),
    # view women_ethnic
    path('women_ethnic', women_ethnic , name='women_ethnic'),
# -----------------------------------------------------------


# ----------------------------------------------------------------------------
    # view designer profile
     path('designer/<int:pk>/', designer_profile, name='designer_profile'),
# -----------------------------------------------------------------------------



# -------------------------------------------------------------------------------------------------
    # customer url's

    # customer dashboard
    path('customer_dashboard',customer_dashboard, name='customer_dashboard'),
    # customer user page 1
    path('userpage1',userpage1, name='userpage1'),
    # customer user page 2
    path('userpage2',userpage2, name='userpage2'),
    # customer user page 1
    path('user_profile',user_profile, name='user_profile'),
    # edit customer address function
    path('edit_customer_address',edit_customer_address, name='edit_customer_address'),
    
        # history
    path('history', history, name='history'),

    # whishlist (view , add , remove) 
    path('wishlist', wishlist, name='wishlist'),
    path('add/<int:product_id>', add_to_wishlist, name='add_to_wishlist'),
    path('remove/<int:pk>', remove_from_wishlist, name='remove_from_wishlist'),

    # cart
    path('cart/<int:product_id>', cart, name='cart'),

    # order
    path('create_order/<int:product_id>', create_order, name='create_order'),
    # pending orders
    path('orders_view', orders_view, name='orders_view'),
    # review
    path('submit_review/<int:order_id>/', submit_review, name='submit_review'),


    # designer - order functions
    path('designer_orders', designer_orders, name='designer_orders'),
    path('order/<int:order_id>/change_status/', change_order_status, name='change_order_status'),
    path('designers/<int:designer_id>/business/', designer_business, name='designer_business'),



]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

TFP/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from designers.models import Product


class MyAccountManager(BaseUserManager):
    def create_user(self, user_name, mobile, email, password=None):
        if not email:
            raise ValueError("User must have an email address")
        if not mobile:
            raise ValueError("User must have a mobile Number")
        user = self.model(
            email=self.normalize_email(email),
            mobile=mobile,
            user_name=user_name,
        )
        user.is_varified = False
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, user_name, mobile,email, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            mobile=mobile,
            user_name=user_name,

        )
        user.is_admin = True
        user.is_varified = True
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True, blank=False)
    username = models.CharField(max_length=60, unique=False, blank=True)
    mobile = models.CharField(max_length=13, blank=False, unique=True)
    date_joined = models.DateTimeField(verbose_name="date joined", auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="last login", auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_varified = models.BooleanField(default=False)
    is_rejected = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_designer = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["mobile", "username"]

    objects = MyAccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True

    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        ordering = ['-last_login','-date_joined']



class Designer(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=155,null=True,blank=True)
    email = models.EmailField(max_length=255, unique=True)
    phone = models.CharField(max_length=15,unique=True)
    bio = models.TextField(max_length=155,null=True,blank=True)
    logo = models.ImageField(upload_to='media/designer/logo',blank=True,null=True)
   

    def __str__(self):
        return self.name
    
    
    def get_products(self):
        return Product.objects.filter(designer=self)

class CustomerProfile(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=155,null=True,blank=True)
    email = models.EmailField(max_length=255, unique=True)
    phone = models.CharField(max_length=15,unique=True)
    house = models.CharField(max_length=25,unique=False)
    landmark = models.CharField(max_length=25,unique=False)
    city = models.CharField(max_length=25,unique=False)
    pincode = models.CharField(max_length=6,unique=False)

    def __str__(self):
        return self.name
    
    def get_full_address(self):
        return f"{self.house}, {self.landmark}, {self.city}, {self.pincode}"

TFP/designers/views.py
from pyexpat.errors import messages
from django.http import HttpResponse
from django.shortcuts import render, redirect
from account.models import CustomerProfile
from designers.forms import ProductForm
from account.models import Designer
from designers.models import Product
from customers.models import Order

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import DesignerProfileForm, ProductForm, StockForm


# Create your views here.

# designer dashboard view
# def designer_dashboard(request):
#     user = request.user
#     designer = Designer.objects.get(user=user)
#     return render(request, "designerViewProducts.html", {'designer': designer})

from .forms import DesignerProfileForm

def designer_dashboard(request):
    user = request.user
    designer = Designer.objects.get(user=user)
    if request.method == 'POST':
        form = DesignerProfileForm(request.POST, request.FILES, instance=designer)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile has been updated!')
    else:
        form = DesignerProfileForm(instance=designer)
    return render(request, 'designerViewProducts.html', {'form': form})


# add product view
def add_product_view(request):
    return render(request,'addPrd.html',{})

# delete product view
def delete_product_view(request):
    return render(request,'delete_product.html',{})

# base html
def base(request):
    return render(request,'designer_base.html',{})

# update stock view
def update(request):
    return render(request,'stockMan.html',{})

# designer registration page view
def designer_registration(request):
    return render(request,'DesigReg.html',{})

# edit basic info of designer(dp and logo)
def edit_info(request):
    return render(request,'editInfo.html',{})


# =====================================================================================================


@login_required
def add_product(request):
    if not request.user.is_designer:
        return redirect('designer_dashboard')

    designer = Designer.objects.get(user=request.user)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.designer = designer
            product.category1 = form.cleaned_data['category1']
            product.category2 = form.cleaned_data['category2']
            product.save()
            form.save_m2m()
            print(request.POST)
            messages.success(request, 'Product added successfully.')
            return redirect('designer_dashboard')
    else:
        form = ProductForm() 

    return render(request, 'addPrd.html', {'form': form})


# =============================================================================================
# view products
# --------------------

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Product

@login_required
def designer_profile(request):
    designer = request.user.designer  # get the designer object of the logged-in user
    products = Product.objects.filter(designer=designer)  # get all products with the designer object
    context = {'designer': designer, 'products': products}
    return render(request, 'designerViewProducts.html', context)


# ==================================================================================================
# edit designer profile
# ===========================


def edit_designer_profile(request):
    designer = Designer.objects.get(user=request.user)
    # designer = request.user.designer # retrieve the designer object
    if request.method == 'POST':
        print(request.POST)
        form = DesignerProfileForm(request.POST, request.FILES, instance=designer)
        if form.is_valid():
            form.save() # save the updated form data to the designer object
            return redirect('designer_dashboard') # redirect to the designer's profile page
    else:
        form = DesignerProfileForm(instance=designer) # pre-populate the form with the current designer's information
    return render(request, 'editInfo.html', {'form': form})


# =======================================================================================================
# product delete
# =====================

# from django.shortcuts import get_object_or_404, redirect

# def delete_product(request, pk):
#     product = get_object_or_404(Product, pk=pk)
#     if request.method == 'POST':
#         product.delete()
#         return redirect('delete_product_view')
#     return render(request, 'delete_product.html', {'product': product})

from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages

def delete_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product.delete()
        messages.success(request, 'Product deleted successfully.')
        return redirect('designer_dashboard')
    return render(request, 'delete_product.html', {'product': product})


# ====================================================================================================
# update stock
# ============================

def update_stock(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        form = StockForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Stock updated successfully.')
            return redirect('designer_dashboard')
        else:
            messages.error(request, 'Error updating stock.')
    else:
        form = StockForm(instance=product)

    context = {'product': product, 'form': form}
    return render(request, 'stockMan.html', context)

# ---------------------------------------------------------------------------------------------------

# designer order status

from django.shortcuts import render, redirect
from customers.models import Order

# @login_required
# def designer_orders(request):
#     user = request.user
#     customer = CustomerProfile.objects.get(user=user)
#     designer = get_object_or_404(Designer, user=request.user)
#     context = {'designer': designer, 'customer': customer}
#     return render(request, 'designer_order.html', context)


@login_required
def designer_orders(request):
    user = request.user
    designer = get_object_or_404(Designer, user=user)
    orders = Order.objects.filter(designer=designer)
    order_details = []
    for order in orders:
        customer_profile = CustomerProfile.objects.get(user=order.customer)
        address = f"{customer_profile.house}, {customer_profile.landmark}, {customer_profile.city} - {customer_profile.pincode}"
        order_detail = {'order': order, 'address': address}
        order_details.append(order_detail)
    context = {'designer': designer, 'order_details': order_details}
    return render(request, 'designer_order.html', context)


# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-==-=-=-=-=-=-=-=-=-=-=-=-=-=-=-===-=-=-=-==-=-=-=-=-=-=-=-=-=-=-=

# @login_required
# def change_order_status(request, order_id):
#     order = get_object_or_404(Order, id=order_id)
#     if order.designer.user != request.user:
#         return redirect('home')
#     if order.status == 'pending':
#         order.status = 'done'
#         order.save()
#     return redirect('designer_order')

@login_required
def change_order_status(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    if order.designer.user != request.user:
        return redirect('home')
    if order.status == 'pending':
        order.status = 'done'
        order.save()
        product = order.product
        product_name = product.prd_name
        product.small += order.product.small
        product.medium += order.product.medium
        product.large += order.product.large
        product.extra_large += order.product.extra_large
        product.save()
        messages.success(request, f"The order for {product_name} has been shipped.")
    return redirect('designer_orders')




# designer business
@login_required
def designer_business(request, designer_id):
    designer_business = Order.objects.filter(designer_id=designer_id, status='done')
    context = {'orders': designer_business}
    return render(request, 'designer_business.html', context)

TFP/templates/approve_order.html
{% extends 'designer_base.html' %}

{% block content %}
  <h1>Approve Order</h1>
  <p>Are you sure you want to approve the order "{{ order }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Approve</button>
  </form>
{% endblock %}

TFP/templates/customer_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> {% block title %} {% endblock %}</title>

    <!-- css -->
    <!-- style-one -->
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    <!-- style-two -->
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
    <!-- style-three -->
    <link rel="stylesheet" href="{% static 'css/style3.css' %}">
    <!-- desigStyle -->
    <link rel="stylesheet" href="{% static 'css/desgStyle.css' %}">
    <!-- desigStyle -->
    <link rel="stylesheet" href="{% static 'css/desgStyle.css' %}">

    <!-- Jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-latest.min.js"></script>
    

    <!-- JS -->
    <!-- js one -->
    <script src="{% static 'js/javascript1.js' %}"></script>

  <!-- font awesome icons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
    integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

  <!-- google fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

  <!-- bootstrap -->
      <!-- bootstrap -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  
</head>

<body>

  <!-- nav bar -->
  <div class="nav">

    <!-- logo -->
    <div class="logo">
      <h2> <a href="{% url 'userpage1' %}"> The Fashion Project</a></h2>
     </div>

    <!-- search bar -->
    <div class="search">
      <!-- <form action="" method="post">
        <input type="text" class="search-bar" placeholder="search for designers...">
        <button type="submit" class="search-button"><i class="fa fa-search fa-lg"></i></button>
      </form> -->
    </div>

    <!-- user profile -->
    <div>
      <a href="{% url 'user_profile' %}" class="user-profile"><i title="User Profile" class="fa-regular fa-user fa-lg"></i></a>
    </div>

    <!-- whish list -->
    <div >
      <a href="{% url 'wishlist' %}" class="whish-list"><i title="whish list" class="fa-regular fa-heart fa-lg"></i></a>
    </div>

    <!-- cart -->
    <div >
      <!-- <a href="" class="cart"><i title="cart" class="fa-solid fa-bag-shopping fa-lg"></i></a> -->
    </div>

    <!-- logout -->
    <div >
        <a href="{% url 'logout_view' %}" class="logout"><i title="Sign out" class="fa-solid fa-right-from-bracket fa-lg"></i></a>
    </div>

  </div>

  <!-- space -->
  <div class="space">

  </div>

{% block content %}

{% endblock %}

<div class="footer-cust">
  <p>the fashion project @2023</p>
</div>

</body>
</html>

TFP/templates/designerEdit.html
{% extends 'designer_base.html' %}

{% block title %}
Products
{% endblock%}

{% load static %}

{% block content %}


<!-- ḍesigner products -->

<div class="prd-det">
    <!-- main img sec-->
    <div class="sec-2">
        <img src="{% static 'imges/skel.jpg' %}" alt="">
    </div>

        <!-- sub img sec -->
        <div class="sec-1">
            <img src="{% static 'imges/skel.jpg' %}" alt="">
            <img src="{% static 'imges/skel.jpg' %}" alt="">
            <img src="{% static 'imges/skel.jpg' %}" alt="">
        </div>
    
    <!-- desginer/product details -->
    <div class="sec-3">
        <div>
            <!-- prd det -->
            <h3>Product Details</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum quis, aperiam mollitia ipsam ratione
                qui laboriosam nobis libero, aliquid nulla eaque, corporis ea alias? Architecto impedit fugiat enim
                necessitatibus maiores.</p>

            <!-- price -->
            <h3 id="pr">&#x20b9; 799.00 </h3>
        </div>
    </div>
</div>


{% endblock%}

TFP/templates/designerView.html
{% extends 'customer_base.html' %}

{% block title %}
User Home | TFP 
{% endblock%}

{% load static %}


{% block content %}


  <!-- space -->
  <div class="space">

  </div>
  
  <!-------------------------------------------------------------------------------------------------------------- -->    

<!-- desigener sec -->

<div class="desig-prof">
    <!-- desig dp -->
    <div class="desig-head">
        <div class="dp">
            <img src="{{ designer.logo.url }}" alt="">
        </div>
        <h2>{{ designer.name }}</h2>
    </div>

    <!-- bio and other details -->
    <div class="bio">
        <table>
            <tr>
                <td class="bold">Contact</td>
                <td>{{ designer.email }}</td>
            </tr>
            <tr>
                <td class="bold">Phone</td>
                <td>{{ designer.phone }}</td>
            </tr>
            <tr>
                <td class="bold">Bio</td>
                <td>{{ designer.bio }}</td>
            </tr>
        </table>
    </div>

</div>

{% if designer.get_products %}
<!-- ḍesigner products -->
    {% for product in designer.get_products %}
<!-- ḍesigner products -->

<div class="prd-det">
    <!-- main img sec-->
    <div class="sec-2">
        <img id="mainImage{{product.pk}}" src="{{ product.image1.url }}" alt="{{ product.prd_name }}">
    </div>
    
    <!-- sub img sec -->
    <div class="sec-1">
        <img src="{{ product.image1.url }}" alt="{{ product.prd_name }}" onclick="changeImage('{{ product.pk }}', this)">
        <img src="{{ product.image2.url }}" alt="{{ product.prd_name }}" onclick="changeImage('{{ product.pk }}', this)">
        <img src="{{ product.image3.url }}" alt="{{ product.prd_name }}" onclick="changeImage('{{ product.pk }}', this)">
        <img src="{{ product.image4.url }}" alt="{{ product.prd_name }}" onclick="changeImage('{{ product.pk }}', this)">
    </div>
    
    


    <!-- desginer/product details -->
    <div class="sec-3">
        <div>
            <!-- prd det -->
            <h3>{{ product.prd_name }}</h3>
            <p>
        <p>Category : {{ product.category1 }} {% if product.category2 %} > {{ product.category2 }}{% endif %}</p>           
            </p>
            <!-- spec table -->
            <table>
                <tr>
                    <td class="sp-tt">Size & Fit</td>
                    <td class="sp-td">{{ product.fit }}</td>
                </tr>
                <tr>
                    <td class="sp-tt">Material</td>
                    <td class="sp-td">{{ product.material }}</td>
                </tr>
                <tr>
                    <td class="sp-tt">Care</td>
                    <td class="sp-td">{{ product.care }}</td>
                </tr>
                <tr>
                    <td class="sp-tt">Occasion</td>
                    <td class="sp-td">{{ product.occasion }}</td>
                </tr>
            </table>

            <hr>

                        <!-- price -->
                        <h3 id="pr" style="padding-right: 1rem;">Price : &#x20b9; {{ product.price }}</h3>

            <hr>
            
            <div class="btns">

                <button class="buy-btn"><a href="{% url 'cart' product_id=product.id %}">Buy Now</a></button>
                <button title="add to whishlist" class="whish-btn"><a href="{% url 'add_to_wishlist' product_id=product.id %}"><i class="fa fa-heart fa-lg"></i></a></button>
   
            </div>

            <hr>

            <div style="display: flex; flex-direction: row; justify-content: space-around;">

            <!-- remove btn -->
            <script>
                function confirmDelete() {
                  var result = confirm("Are you sure you want to delete this product?");
                  if (result) {
                    return true;
                  } else {
                    return false;
                  }
                }
            </script>
                

            </div>
        </div>
    </div>
</div>

<hr>

{% endfor %}
{% endif %}

{% endblock%}

TFP/templates/designer_business.html
{% extends 'designer_base.html' %}

{% block title %}
View Business
{% endblock%}

{% load static %}

{% block content %}

{% for order in orders %}
  <div class="cart-tabel">
    <table>
        <!-- table content -->
        <hr>

        <tr>
            <th>Prd Name</th>
            <th></th>
            <th>Size</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total</th>
            <th>Booking Date</th>
            <th>Status</th>
            <th>To Address</th>
        </tr>

        <tr>
            <td>{{ order.product.prd_name }}</td>
            <td>
                <img src="{{ order.product.image1.url }}" alt="{{ product.prd_name }}" style=" width : 6rem; height: auto;">
            </td>
            <td>{{ order.size }}</td>
            <td>{{ order.quantity }}</td>
            <td>{{ order.price }}</td>
            <td>{{ order.total }}</td>
            <td>{{ order.booking_date|date:"F d, Y" }}</td>
            <td>{{ order.status }}</td>
            <td>{{ order.to_address }}</td>
        </tr>
    </table>
</div>
{% empty %}
  <p>No completed orders yet.</p>
{% endfor %}

 
{% endblock %}

TFP/templates/designer_order.html
{% extends 'designer_base.html' %}

{% block title %}
Shipping Requests
{% endblock%}

{% load static %}

{% block content %}

{% if messages %}
    <div class="messages">
        {% for message in messages %}
            <p style="text-align: center; color: green;" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
        {% endfor %}
    </div>
{% endif %}

{% for order in designer.orders.all %}
    {% if order.status == 'pending' %}
        <!-- cart table -->
        <div class="cart-tabel">
            <table>
                <!-- table content -->
                <hr>
                <tr>
                    <th>Prd Name</th>
                    <th></th>
                    <th>Size & Quantity</th>
                    <th>Price</th>
                    <th>Total</th>
                    <th>Shipping Address</th>
                    <th></th>
                </tr>

                <tr>
                    <td>{{ order.product.prd_name }}</td>
                    <td>
                        <img src="{{ order.product.image1.url }}" alt="{{ product.prd_name }}" style=" width : 6rem; height: auto;">
                    </td>
                    <td>{{ order.size }} | {{ order.quantity }}</td>
                    <td>{{ order.price }} </td>
                    <td>{{ order.total }}</td>
                    <td>
                        {% for order_detail in order.customer.customerprofile_set.all %}
                            {% if order_detail == order.customer.customerprofile_set.first %}
                                {{ order_detail.house }}, {{ order_detail.landmark }}, {{ order_detail.city }} - {{ order_detail.pincode }}
                            {% endif %}
                        {% empty %}
                            <p>No shipping address found.</p>
                        {% endfor %}
                    </td>
                    <td>
                        <form action="{% url 'change_order_status' order.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-success btn-sm">Mark as Shipped</button>
                        </form>
                    </td>
                </tr>
            </table>
        </div>
    {% endif %}
{% empty %}
    <p>No completed orders yet.</p>
{% endfor %}



{% endblock %}